name = "LibASICamera"
uuid = "d52fb188-cbdc-4a2a-a9d4-49c222ce4b32"
authors = ["Max Freudenberg"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"
CEnum = "0.2"
